### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by d3p1** [d3p1/jekyll-theme-codify#1]
## Description

Create a custom [Jekyll theme](https://jekyllrb.com/docs/themes/) based on one of the greatest Jekyll theme templates: [Chirpy Jekyll Theme](https://github.com/cotes2020/jekyll-theme-chirpy).

## Solution

Implement a [Jekyll theme](https://jekyllrb.com/docs/themes/) using the [Chirpy Jekyll Theme](https://github.com/cotes2020/jekyll-theme-chirpy) as its parent.
Check if it is possible to create a [Jekyll theme](https://jekyllrb.com/docs/themes/), using the `bundle exec jekyll new-theme jekyll-theme-codify` command, that has as its dependencies the `jekyll-theme-chirpy` and extends from it configuring it in the `theme` options of the `_config.yml` file.
If there is a problem with the above procedure, it will be necessary to fork/copy the [Chirpy Jekyll Theme repository](https://github.com/cotes2020/jekyll-theme-chirpy) and customize its files directly (instead of using an [override method](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) as it would be possible with the above method).
After the required modifications to create a custom _Look&Feel_, [publish the theme gem](https://jekyllrb.com/docs/themes/).   

## Additional information

- Check the [related theme documentation](https://chirpy.cotes.page/posts/getting-started/)
- Check the [official Jekyll theme documentation](https://jekyllrb.com/docs/themes/)

**Comment by d3p1** [comment]
At the current moment ([commit 89f4eb91533334248c9a1b2bd07171c95b2132c4][1]), it was build and push a [jekyll-theme-codify gem][2]. This theme was developed based on the idea of extend the [jekyll-theme-chirpy theme][3]. In this way, was defined the [`jekyll-theme-chirpy` as a runtime dependency of the theme][4].

Then, it was tried to install this theme in a site. It was used the [d3p1/jekyll:nginx-alpine3.18 image][5] and it was run the following command:

```
bundle add jekyll-theme-chirpy
```

After that, was removed the `minimal` theme from the `Gemfile`:

```diff
- gem "minima", "~> 2.5"
```

And it was added the `jekyll-theme-codify` as the `theme` in the `_config.yml` file:

```diff
- theme: minima
+ theme: jekyll-theme-codify
```

Finally, it was run:

```
bundle install
```

But when it was run:

```
/main.docker-entrypoint.sh bundle exec jekyll build --config _config.yml,_config.dev.yml
```

The following error was dispatched:

```
Theme Config file: /home/jekyll/.config/ruby/bundle/gems/jekyll-theme-codify-0.0.0/_config.yml
Dependency Error: Yikes! It looks like you don't have jekyll-theme-chirpy or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll-theme-chirpy gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- jekyll-theme-chirpy' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
```

So, it seems that it is not possible to develop a [Jekyll theme][6] that extends from other [Jekyll theme][6].
The development will be continued using the [`jekyll-theme-chirpy` source code directly][3]

[1]: https://github.com/d3p1/jekyll-theme-codify/commit/89f4eb91533334248c9a1b2bd07171c95b2132c4
[2]: https://rubygems.org/gems/jekyll-theme-codify
[3]: https://github.com/cotes2020/jekyll-theme-chirpy
[4]: https://github.com/d3p1/jekyll-theme-codify/blob/89f4eb91533334248c9a1b2bd07171c95b2132c4/jekyll-theme-codify.gemspec#L28
[5]: https://hub.docker.com/layers/d3p1/jekyll/nginx-alpine3.18/images/sha256-f9ee2b6f458f9633f525532f4c6777036ae60a3ac84a0a692b9f38d23dda372c?context=explore
[6]: https://jekyllrb.com/docs/themes/

**Comment by d3p1** [comment]
```
/main.docker-entrypoint.sh bundle exec jekyll build --watch --config _config.yml,_config.env.yml

/home/jekyll/.config/ruby/bundle/gems/jekyll-4.3.2/lib/jekyll/theme.rb:86:in `rescue in gemspec': The jekyll-theme-codify theme could not be found. (Jekyll::Errors::MissingDependencyException)

/usr/lib/ruby/3.2.0/rubygems/dependency.rb:316:in `to_specs': Could not find 'jekyll-theme-codify' (>= 0) - did find: [jekyll-theme-codify-0.0.0.pre.alpha.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.local/share/gem/ruby/3.2.0:/usr/lib/ruby/gems/3.2.0:/home/jekyll/.config/ruby/bundle' , execute `gem env` for more information
```

**Comment by d3p1** [comment]
Following the last comment, it was also added to the [gem][1] a [`_config.yml`][2] that extends the [`jekyll-theme-chirpy`][3] but, after trying to install the theme in a site using the process mentioned in the last comment, the same error occurs.

[1]: https://rubygems.org/gems/jekyll-theme-codify
[2]: https://github.com/d3p1/jekyll-theme-codify/blob/6ff0b860b8c3a2c1cbf9619f69f736fc48de2258/_config.yml
[3]: https://github.com/cotes2020/jekyll-theme-chirpy
